%%/************************************************************************/
%%/* (c) 2016 Ecole Polytechnique Federale de Lausanne                    */
%%/* All rights reserved.                                                 */
%%/*                                                                      */
%%/* EPFL grants a non-exclusive and non-transferable license for non     */
%%/* commercial use of the Software for education and research purposes   */
%%/* only. Any other use of the Software is expressly excluded.           */
%%/*                                                                      */
%%/* Redistribution of the Software in source and binary forms, with or   */
%%/* without modification, is not permitted.                              */
%%/*                                                                      */
%%/* Written by Andrii Maksai.                                            */
%%/*                                                                      */
%%/* http://cvlab.epfl.ch/research/balltracking                           */
%%/* Contact <andrii.maksai@epfl.ch> for comments & bug reports.          */
%%/************************************************************************/

function [ ] = define_data_format( )
    global FORMAT; FORMAT = [];

    FORMAT.DETECTION = struct(...
                              'Pos', zeros(0, 3),...
                              'W', [],...
                              'Space', [],...
                              'Cost', [],...
                              'X', [],...
                              'Y', [],...
                              'Z', [],...
                              'tmp', []);

    FORMAT.TRACK = struct(...
                          'T',[],...
                          'X',[],...
                          'Y',[],...
                          'Z',[],...
                          'Pos', zeros(0, 3),...
                          'Space', [],...
                          'W', [],...
                          'Cost', [],...
                          'tmp', [],...
                          'Node', [],...
                          'PeopleNode',[]...
                          );

    FORMAT.NODE = struct(...
                        'Time',    zeros(1,1),...
                        'X',    [],...
                        'Y',    [],...
                        'Z',    [],...
                        'Pos',  [],...
                        'Space',   [],...
                        'Info',    [],...
                        'Incoming', [],...
                        'Outgoing', [],...
                        'tmp', [],...
                        'SumPChildren', [],...
                        'log_Px_mz', [],...
                        'Pm_x', [],...
                        'Pm_xz', [],...
                        'log_Px_z', [],...
                        'local_Px_z', [],...
                        'PeopleNode', []...
                        );

    FORMAT.EDGE = struct(...
                        'A',       zeros(1,1),...
                        'B',       zeros(1,1),...
                        'W',       zeros(1,1),...
                        'VarId',   zeros(1,1),...
                        'Marker',  zeros(1,1),...
                        'tmp',     []...
                        );

    FORMAT.POM = struct(...
                        'Loc', [],...
                        'Gloc', [],...
                        'Ort', [],...
                        'W', [],...
                        'X', [],...
                        'Y', [],...
                        'Z', [],...
                        'Pos', zeros(0, 3),...
                        'Grid', []);
end

